I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 26, in script
    e "You've created a new Ren'Py game."
Exception: Sayer 'e' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 26, in script
    e "You've created a new Ren'Py game."
  File "C:\Users\wawa\Desktop\renpy-8.1.0-sdk\renpy\ast.py", line 890, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\wawa\Desktop\renpy-8.1.0-sdk\renpy\ast.py", line 783, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'e' is not defined.

Windows-10-10.0.22621 AMD64
Ren'Py 8.1.0.23051307
MonkeyVisualNovel 1.0
Sun May 21 14:10:44 2023
